# Generated by Django 5.0.6 on 2024-06-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_answer',
            field=models.JSONField(default=dict, verbose_name='user answer'),
        ),
    ]
