# Generated by Django 5.0.6 on 2024-06-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_answer_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='question data'),
        ),
    ]
